### PR TITLE
MVP Documentation Site

### PR DESCRIPTION
**Pull request by kpsuperplane**
Todo:
- Detailed API docs for 
   - [x] Rely
   - [x] Console
   - [x] Pastel
   - [x] Refmterr
   - [x] FCP
- [ ] Better logo animation
- [ ] Better banner logo
- [x] Basic help page
- [x] Documentation Overview
- [x] Homepage with demos

Preview:
https://kpsuperplane.github.io/reason-native

Builds off many of the excellent readme's written by @bandersongit

### CODE REVIEW

**Comment by kyldvs** [comment]
This is awesome!

**Comment by jordwalke** [comment]
Want to pick this up @kpsuperplane ?

**Comment by jordwalke** [comment]
@kyldvs Should we develop this on another branch other than master so that we can just commit very easily to it and never sync it internally?

**Comment by kpsuperplane** [comment]
good idea @jordwalke! Sorry for the relative inactivity on my end, I've been adapting back to school life . Will start working on this again :D

**Comment by kyldvs** [comment]
Perhaps `reason-native/site`?

**Comment by kpsuperplane** [comment]
@kyldvs do you have any idea why my builds are failing? AFAIK it's up to date with master and none of my changes are build related

**Comment by kyldvs** [comment]
Oh no, I was trying to change this to be against the branch "Website" I just created and now it looks like I broke something

**Pull request closed without merging**
