### PR TITLE
describe skip

### PR DESCRIPTION
**Pull request by bandersongit**
Describe skip feature. Ended up using obj.magic in the top level describeSkip implementation to give a good API (the code that uses it is never actually called by design), curious to see if you guys have a cleaner solution that doesn't require a lot of refactoring.

### CODE REVIEW

**Comment by kyldvs** [comment]
I'm concerned with how frequently we are starting to use `Obj.magic` in this repo. It's something we should avoid. Is there a way we can refactor without using it?

It looks like the problem might be custom extensions. Should we make `extendDescribe` return a record of all the "describe" variations.

```
let {describe, describeSkip} = extendDescribe(...);
```

Will that refactor solve the issues?

**Comment by kyldvs** [comment]
Alternatively, we could have `extendDescribe` return a first class module, or be a functor and the resulting module gets opened to put the different variations of describe in scope so they do not need to be enumerated.

**Comment by bandersongit** [comment]
> I'm concerned with how frequently we are starting to use `Obj.magic` in this repo. It's something we should avoid. Is there a way we can refactor without using it?

I don't think the frequency is really something to consider. I think the other usages (it is kind of the point of Console, and providing helpful hints in CollectionMatchers and isn't accomplishable in another manner without worsening the API) make sense. I do agree that this is less than ideal.

> It looks like the problem might be custom extensions. Should we make `extendDescribe` return a record of all the "describe" variations.
> 
> ```
> let {describe, describeSkip} = extendDescribe(...);
> ```
> Will that refactor solve the issues?

The problem is in fact extendExpect, what you propose would certainly be a solution, however that would be a backwards breaking change, which I don't think is worth it here. I think there is a real usability advantage in having describeSkip not being a product of extendExpect in that consumers can just use it the same way everywhere.

**Comment by bandersongit** [comment]
> Alternatively, we could have `extendDescribe` return a first class module, or be a functor and the resulting module gets opened to put the different variations of describe in scope so they do not need to be enumerated.

I think this is an interesting idea, my initial thought is that this would be more confusing than the current API for extendDescribe (and it is clearly backwards breaking) because you would be opening different modules in different test files (e.g. you wouldn't need to/couldn't open TestFramework anymore in extended describes and having multiple sets of custom matchers could be more confusing).

**Comment by kyldvs** [comment]
> a real usability advantage in having describeSkip not being a product of extendExpect

I think it has to look like the same extensions though for `descrbeSkip` to make sense. If you write

```
let describe = extendDescribe(...);

describe("foo", ({test}) => {
  test("bar", ({expect}) => {
    expect.ext.custom(thing).toWork();
  });
});
```

Then `describeSkip` needs to have the same type for `expect` and have `ext.custom` otherwise you cannot just swap `describe` for `describeSkip`. While right now we can use magic and hide it because it will not run due to it being "skipped", in the future if we want to add `describeOnly` it will have to have the functioning extension `ext.custom` in order to work.

**Comment by bandersongit** [comment]
> > a real usability advantage in having describeSkip not being a product of extendExpect
> 
> I think it has to look like the same extensions though for `descrbeSkip` to make sense. If you write
> 
> ```
> let describe = extendDescribe(...);
> 
> describe("foo", ({test}) => {
>   test("bar", ({expect}) => {
>     expect.ext.custom(thing).toWork();
>   });
> });
> ```
> Then `describeSkip` needs to have the same type for `expect` and have `ext.custom` otherwise you cannot just swap `describe` for `describeSkip`. While right now we can use magic and hide it because it will not run due to it being "skipped", in the future if we want to add `describeOnly` it will have to have the functioning extension `ext.custom` in order to work.

You are right, I think describeOnly/testOnly will necessitate this change. That said, that feature requires some structural changes as well (separating discovery from execution), which I think aren't as immediately urgent. 

I think my proposal is to keep the Obj.magic for now (rather than using an option which I proposed in person) and switch to a functor with a buildable config for describeOnly/testOnly and batch that with some other breaking changes (mostly moving more things into the Rely.Make functor0.

**Pull request closed without merging**
